function wr_save_fig(base_fname, note)
if nargin<2
	note='';
end
save_fig(['fig/fig/',base_fname,'.fig'], ...
	['fig/pdf/',base_fname,'.pdf'], ...
	['fig/pdf/cuts/',base_fname,'_notitle.pdf'], ...
	'', ...
	['fig/pdf/cuts/',base_fname,'_bare.pdf'], ...
	['fig/titles/',base_fname,'_title.txt'], ...
	['fig/notes/',base_fname,'_note.txt'], ...
	['fig/notes/tex/',base_fname,'_note.tex'], ...
	note)
end